In [3]:
import numpy as np

x = np.arange(1, 4)
print(x)

[1 2 3]


In [10]:
M = np.random.rand(2, 3)
M.shape
print(M)

[[ 0.36029935  0.54467995  0.36218917]
 [ 0.28679795  0.30509256  0.13293092]]


In [12]:
g = np.dot(M, x)
print(g.shape, g)

((2L,), array([ 2.53622678,  1.29577584]))


In [14]:
z = np.random.rand(3)
print(z)
r = z*x
print(r)

[ 0.59380159  0.78401609  0.86628231]
[ 0.59380159  1.56803218  2.59884692]


In [17]:
e = np.dot(z, x)
print(e)
print(r.sum())

4.76068068289
4.76068068289


In [18]:
M_inv = np.linalg.inv(M)
print(M_inv)

LinAlgError: Last 2 dimensions of the array must be square

In [19]:
B = np.random.rand(3, 3)
print(B)

[[ 0.8466469   0.12583629  0.44747289]
 [ 0.9741643   0.04868454  0.52276786]
 [ 0.90829986  0.15119802  0.57515426]]


In [23]:
B_inv = np.linalg.inv(B)
print(B_inv)
print(np.dot(B_inv, B))

[[  6.50527407   0.6013595   -5.60772197]
 [ 10.89279022 -10.26167032   0.85236809]
 [-13.13683704   1.74793013  10.37046424]]
[[  1.00000000e+00  -1.11022302e-16   0.00000000e+00]
 [  1.66533454e-15   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.22044605e-16   1.00000000e+00]]
