In [16]:
%matplotlib inline

# from scipy.signal import gaussian
import numpy as np
import matplotlib.pyplot as plt

def sin_exp(x):
    return np.sin(x)*np.exp(x)

def gaussian(x, x0, A, sig):
    return A*np.exp(-(x-x0)**2/(2.*sig**2))

x = np.linspace(-2, 2, 5)
y = np.linspace(-2, 2, 5)
# y = np.exp(x)
# y1 = sin_exp(x)
# y2 = gaussian(x, 0, 2, 1)
xx, yy = np.meshgrid(x, y)
print(xx)
print(yy)


# plt.plot(x, y)
# plt.plot(x, y1)
# plt.plot(x, y2)
plt.show()

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
[[-2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]]
