# prime.py

In [199]:
import numpy as np

def find_primenumber(start, end):
    if start <= 1:
        start = 2
    arr = np.arange(start, end+1)
    prime = []
    for k in arr:
        j = 0
        for a in range(1, end+1):
            if k % a == 0:
                j += 1
        if j <= 2:
            prime.append(k)
    return prime
            
x = find_primenumber(1, 1000)
print x
print len(x)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]
168


### Main code

In [194]:
import numpy as np

def primenumbers(start, end):
    prime = []
    if start <= 3:
        prime.append(2), prime.append(3)
        start = 2
    arr = np.arange(start, end+1)
    
    
    
    

[2, 3, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 121, 127, 131, 137, 139, 143, 149, 151, 157, 163, 167, 169, 173, 179, 181, 187, 191, 193, 197, 199, 209, 211, 221, 223, 227, 229, 233, 239, 241, 247, 251, 253, 257, 263, 269, 271, 277, 281, 283, 289, 293, 299, 307, 311, 313, 317, 319, 323, 331, 337, 341, 347, 349, 353, 359, 361, 367, 373, 377, 379, 383, 389, 391, 397, 401, 403, 407, 409, 419, 421, 431, 433, 437, 439, 443, 449, 451, 457, 461, 463, 467, 473, 479, 481, 487, 491, 493, 499, 503, 509, 517, 521, 523, 527, 529, 533, 541, 547, 551, 557, 559, 563, 569, 571, 577, 583, 587, 589, 593, 599, 601, 607, 611, 613, 617, 619, 629, 631, 641, 643, 647, 649, 653, 659, 661, 667, 671, 673, 677, 683, 689, 691, 697, 701, 703, 709, 713, 719, 727, 731, 733, 737, 739, 743, 751, 757, 761, 767, 769, 773, 779, 781, 787, 793, 797, 799, 803, 809, 811, 817, 821, 823, 827, 829, 839, 841, 851, 853, 857, 859, 863, 869, 871, 877, 881, 883, 887,

In [ ]:
arr = np.arange(10, 20)
x = arr%2
y = arr%3
z = zip(x,y)
print x
print y
idx = x > 0
idy = y > 0
print idx
print idy
prime = []
q = zip(idx, idy)
for i, j in q:
    if i and j == True:
        print 'ugly'
        print i, j

In [144]:
arr = np.arange(10,20)
x = arr%2 > 0
y = arr%3 > 0
q = zip(x,y)
print x
print y
print q
prime = []
for ind, val in enumerate(q):
    if val == (True, True):
        print 'Yay'
        

[False  True False  True False  True False  True False  True]
[ True  True False  True  True False  True  True False  True]
[(False, True), (True, True), (False, False), (True, True), (False, True), (True, False), (False, True), (True, True), (False, False), (True, True)]
Yay
Yay
Yay
Yay


In [158]:
arr = np.arange(10,20)
x = arr%2 > 0
y = arr%3 > 0
q = zip(x,y)
print 'Array: ',arr
print 'x: ',x
print 'y: ',y
print 'q: ',q
j = enumerate(q)
prime = []
for ind, val in j:
    if val == (True, True):
        prime.append(arr[ind])
        
print prime

Array:  [10 11 12 13 14 15 16 17 18 19]
x:  [False  True False  True False  True False  True False  True]
y:  [ True  True False  True  True False  True  True False  True]
q:  [(False, True), (True, True), (False, False), (True, True), (False, True), (True, False), (False, True), (True, True), (False, False), (True, True)]
[11, 13, 17, 19]


In [205]:
x = np.arange(11, 30)
y = np.arange(1, 30)
for val in y:
    print x/val

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[ 5  6  6  7  7  8  8  9  9 10 10 11 11 12 12 13 13 14 14]
[3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9]
[2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6 7 7]
[2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5]
[1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4]
[1 1 1 2 2 2 2 2 2 2 3 3 3 3 3 3 3 4 4]
[1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3]
[1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 3 3]
[1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
[1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2]
[0 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2]
[0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2]
[0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2]
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
[0

# plot_antisym.py